language: node_js

node_js:
  - 8

git:
  depth: 1

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

script:
  yarn $TEST_TYPE

env:
  matrix:
    - TEST_TYPE=build
    - TEST_TYPE=lint
    - TEST_TYPE=test
    - TEST_TYPE=coveralls
